backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "images"

collections:
  - name: 'card'
    label: 'Card'
    folder: 'Images/Projects'
    create: true
    fields:
      - {label: "Featured Image", name: "thumbnail", widget: "image"}